apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: docker.io/DOCKERHUB_REPO_NAME/practice-skaffold # 変更箇所 DOCKERHUB_REPO_NAME
    docker:
      dockerfile: ./Dockerfile
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  helm:
    releases:
    - name: practice-skaffold
      chartPath: skaffold-helm
      valuesFiles: [ skaffold-helm/values.yaml ]
      artifactOverrides:
        image: docker.io/DOCKERHUB_REPO_NAME/practice-skaffold # 変更箇所 DOCKERHUB_REPO_NAME