apiVersion: v1
kind: Service
metadata:
  name: practice-skaffold-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: practice-skaffold