apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: DOCKERHUB_REPO_NAME/practice-skaffold # 変更箇所 DOCKERHUB_REPO_NAME
    docker:
      dockerfile: ./Dockerfile
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - practice-skaffold-*