apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql_pv.name }}
  labels:
    app: wordpress
    tire: mysql
    type: local
spec:
  storageClassName: {{ .Values.mysql_pv.storageClassName }}
  capacity:
    storage: {{ .Values.mysql_pv.storage }}
  accessModes:
    - {{ .Values.mysql_pv.accessModes }}
  hostPath:
    path: {{ .Values.mysql_pv.hostPath }}