apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql_service.name }}
  labels:
    app: mysql
spec:
  type: {{ .Values.mysql_service.type }}
  ports:
    - protocol: {{ .Values.mysql_service.protocol }}
      port: {{ .Values.mysql_service.port }}
      targetPort: {{ .Values.mysql_service.targetPort }}
  selector:
    app: mysql