apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.wordpress_pv.name }}
  labels:
    app: wordpress
    tire: wordpress
    type: local
spec:
  storageClassName: {{ .Values.wordpress_pv.storageClassName }}
  capacity:
    storage: {{ .Values.wordpress_pv.storage }}
  accessModes:
    - {{ .Values.wordpress_pv.accessModes }}
  hostPath:
    path: {{ .Values.wordpress_pv.hostPath }}